name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get install -y g++ cmake

    - name: Configure
      run: |
        mkdir -p .CPP_APP/build  # Create the build directory
        cd .CPP_APP/build         # Change to the build directory
        cmake ..                  # Run CMake pointing to the parent directory of build

    - name: Build
      run: |
        cd .CPP_APP/build         # Change to the build directory
        make                      # Build the project using make

    - name: Run tests
      run: |
        cd .CPP_APP/build         # Change to the build directory
        ./tests/tests_app        # Execute the test application
