name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get install -y g++ cmake

    - name: Configure
      run: |
        mkdir build
        cd build
        cmake ../src  # Adjust path based on where your CMakeLists.txt is located

    - name: Build
      run: |
        cd build
        make  # Adjust this if you have a different build command

    - name: Run tests
      run: |
        cd build
        ./test_app  # Replace 'test_app' with the name of your test executable
