name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get install -y g++ cmake

    - name: Configure
      run: |
        mkdir -p build
        cd build
        cmake ../CPP_APP  # This correctly points to the CPP_APP directory containing CMakeLists.txt

    - name: Build
      run: |
        cd build
        make  # Assumes that make is configured in your CMakeLists.txt

    - name: Run tests
      run: |
        cd build
        ./tests/tests_app  # Replace 'tests_app' with the actual name of your test executable if it's different
