name: C/C++ CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Create build directory
        run: mkdir -p .CPP_APP/build

      - name: Configure CMake
        run: |
          cd .CPP_APP/build
          cmake .. # This assumes CMakeLists.txt is in .CPP_APP

      - name: Build
        run: |
          cd .CPP_APP/build
          make

      - name: Run tests
        run: |
          cd .CPP_APP/build
          ./tests/tests_app
